# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='账号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('belong_to', models.CharField(choices=[('aly', '阿里云'), ('llht', '流量后台'), ('beian', '备案'), ('yxgl', '邮箱管理'), ('domian', '域名'), ('qyqq', '企业QQ'), ('dxpt', '短信平台'), ('internet', '网络'), ('other', '其他')], default='阿里云', max_length=50, verbose_name='账号类别')),
                ('url', models.URLField(max_length=100, verbose_name='登录地址')),
                ('info', models.CharField(max_length=200, verbose_name='备注信息')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='机房名称')),
                ('romm_pos', models.CharField(blank=True, max_length=50, null=True, verbose_name='机房位置')),
                ('cabinet_pos', models.CharField(blank=True, max_length=50, null=True, verbose_name='机柜位置')),
                ('create_at', models.DateField(default='2018-03-26', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '机房表',
                'verbose_name_plural': '机房表',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=40, unique=True, verbose_name='主机名')),
                ('remote_ip', models.CharField(max_length=20, verbose_name='远程连接IP')),
                ('port', models.IntegerField(default=22, verbose_name='连接端口')),
                ('self_ip', models.CharField(max_length=20, verbose_name='内网ip')),
                ('username', models.CharField(default='root', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Account', verbose_name='所属账号')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.IDC', verbose_name='所属机房')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='业务线名称')),
                ('create_at', models.DateField(default='2018-03-26', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '业务线表',
                'verbose_name_plural': '业务线表',
            },
        ),
        migrations.AddField(
            model_name='server',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Team', verbose_name='所属业务线'),
        ),
    ]
