# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='deadtime',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=0, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='server',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='server',
            name='info_sercret',
            field=models.TextField(blank=True, default='请输入密码信息', max_length=400, null=True, verbose_name='登陆密码信息'),
        ),
    ]
