# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20180326_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码')),
                ('tel', models.IntegerField(blank=True, null=True, verbose_name='固定电话')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '联系人管理',
                'verbose_name_plural': '联系人管理',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='域名')),
                ('resolution', models.CharField(max_length=50, verbose_name='解析IP')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('datetime', models.DateField(default='2018-03-26', verbose_name='到期时间')),
                ('info', models.CharField(max_length=200, verbose_name='备注')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Account', verbose_name='所属账号')),
            ],
            options={
                'verbose_name': '域名管理',
                'verbose_name_plural': '域名管理',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=32, verbose_name='座机')),
                ('mobile', models.CharField(max_length=32, verbose_name='手机')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
