# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_connect_domain_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(max_length=20, verbose_name='系统版本')),
                ('kernel_version', models.CharField(max_length=20, verbose_name='内核版本')),
                ('cpu_type', models.CharField(max_length=50, verbose_name='CPU型号')),
                ('cpu_nums', models.IntegerField(default=0, verbose_name='CPU个数')),
                ('mem', models.FloatField(default=0.0, verbose_name='内存')),
                ('swap', models.FloatField(default=0.0, verbose_name='swap')),
            ],
        ),
        migrations.AddField(
            model_name='idc',
            name='mem',
            field=models.FloatField(default=0.0, verbose_name='内存'),
        ),
        migrations.AddField(
            model_name='server',
            name='env_status',
            field=models.CharField(choices=[('test', '测试'), ('prod', '生产'), ('preprod', '预生产'), ('base', '基础')], default='测试', max_length=20, verbose_name='所属环境'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='datetime',
            field=models.DateField(default='2018-03-27', verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_at',
            field=models.DateField(default='2018-03-27', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='team',
            name='create_at',
            field=models.DateField(default='2018-03-27', verbose_name='创建时间'),
        ),
    ]
