# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20180327_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='mem',
        ),
    ]
