# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20180411_0349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name_plural': '资产表'},
        ),
        migrations.AlterModelOptions(
            name='disk_info',
            options={'verbose_name_plural': '硬盘信息'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name_plural': '服务器表'},
        ),
        migrations.AlterField(
            model_name='server',
            name='assets',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='repository.Asset', verbose_name='资产信息'),
        ),
        migrations.AlterField(
            model_name='server',
            name='disk_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_info', to='repository.Disk_info', verbose_name='硬盘信息'),
        ),
    ]
