# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20180411_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='assets',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='repository.Asset', verbose_name='资产信息'),
        ),
        migrations.AlterField(
            model_name='server',
            name='disk_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disk_info', to='repository.Disk_info', verbose_name='硬盘信息'),
        ),
        migrations.AlterField(
            model_name='server',
            name='self_ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='内网ip'),
        ),
    ]
