# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20180411_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='disk_info',
        ),
        migrations.AddField(
            model_name='server',
            name='disk_info',
            field=models.ManyToManyField(blank=True, null=True, to='repository.Disk_info', verbose_name='硬盘信息'),
        ),
    ]
