# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20180411_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='disk_info',
            field=models.ManyToManyField(blank=True, to='repository.Disk_info', verbose_name='硬盘信息'),
        ),
    ]
