# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20180412_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='self_ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='内网ip'),
        ),
    ]
