# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20180412_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='disk_info',
            field=models.ManyToManyField(blank=True, related_name='server_disk', to='repository.Disk_info', verbose_name='硬盘信息'),
        ),
    ]
