# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_auto_20180412_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='update_status',
            field=models.CharField(choices=[('0', '未更新'), ('1', '已更新'), ('2', '更新失败')], default='未更新', max_length=40, verbose_name='更新状态'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='datetime',
            field=models.DateField(default='2018-04-16', verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_at',
            field=models.DateField(default='2018-04-16', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='team',
            name='create_at',
            field=models.DateField(default='2018-04-16', verbose_name='创建时间'),
        ),
    ]
